package com.gsy.swagger.mybatis.mapper;

import com.gsy.swagger.mybatis.po.Courses;
import com.gsy.swagger.mybatis.po.CoursesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoursesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int countByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int deleteByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int deleteByPrimaryKey(String courseno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int insert(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int insertSelective(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    List<Courses> selectByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    Courses selectByPrimaryKey(String courseno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") Courses record, @Param("example") CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int updateByExample(@Param("record") Courses record, @Param("example") CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int updateByPrimaryKeySelective(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    int updateByPrimaryKey(Courses record);
}