package com.gsy.swagger.mybatis.po;

public class Courses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.courseno
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private String courseno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.coursenm
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private String coursenm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.courseno
     *
     * @return the value of courses.courseno
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public String getCourseno() {
        return courseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.courseno
     *
     * @param courseno the value for courses.courseno
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setCourseno(String courseno) {
        this.courseno = courseno == null ? null : courseno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.coursenm
     *
     * @return the value of courses.coursenm
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public String getCoursenm() {
        return coursenm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.coursenm
     *
     * @param coursenm the value for courses.coursenm
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setCoursenm(String coursenm) {
        this.coursenm = coursenm == null ? null : coursenm.trim();
    }
}