package com.gsy.swagger.mybatis.po;

public class ScoreKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.stuid
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private String stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.courseno
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private String courseno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.stuid
     *
     * @return the value of score.stuid
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.stuid
     *
     * @param stuid the value for score.stuid
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.courseno
     *
     * @return the value of score.courseno
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public String getCourseno() {
        return courseno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.courseno
     *
     * @param courseno the value for score.courseno
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setCourseno(String courseno) {
        this.courseno = courseno == null ? null : courseno.trim();
    }
}