package com.gsy.swagger.mybatis.po;

public class Score extends ScoreKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.scores
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private Float scores;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.scores
     *
     * @return the value of score.scores
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public Float getScores() {
        return scores;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.scores
     *
     * @param scores the value for score.scores
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setScores(Float scores) {
        this.scores = scores;
    }
}