package com.gsy.swagger.mybatis.po;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuid
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private String stuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stunm
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    private String stunm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuid
     *
     * @return the value of student.stuid
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public String getStuid() {
        return stuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuid
     *
     * @param stuid the value for student.stuid
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setStuid(String stuid) {
        this.stuid = stuid == null ? null : stuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stunm
     *
     * @return the value of student.stunm
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public String getStunm() {
        return stunm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stunm
     *
     * @param stunm the value for student.stunm
     *
     * @mbggenerated Sun Oct 20 11:29:28 CST 2019
     */
    public void setStunm(String stunm) {
        this.stunm = stunm == null ? null : stunm.trim();
    }
}